[pytest]
DJANGO_SETTINGS_MODULE = room_booking_system.settings
python_files = test_*.py *_tests.py tests.py
addopts = --nomigrations --ignore=room_booking_flutter --ignore=dashboard_analytics.py --ignore=ai --ignore=setup_dashboard.py --ignore=wsgi_pythonanywhere.py
django_debug_mode = True
pythonpath = .
django_find_project = false